apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: polyglot-app

resources:
  - namespace.yaml
  - java-deployment.yaml
  - java-service.yaml
  - python-deployment.yaml
  - python-service.yaml
  - go-deployment.yaml
  - go-service.yaml
  - nodejs-deployment.yaml
  - nodejs-service.yaml
  - ingress.yaml
